MLAGS="CFLAGS=-w -c"
  
all:
	@echo "Make Project begin..."
	cd VIDECMP4 && $(MAKE) $(MFLAGS)
	cd HPATC && $(MAKE) $(MFLAGS)
	cd Demo && $(MAKE) $(MFLAGS)
	@echo "Make project end."
clean:
	@echo "Clean project begin..."
	cd VIDECMP4 && $(MAKE) clean
	cd HPATC && $(MAKE) clean
	cd Demo && $(MAKE) clean
	@echo "Clean project end."
