//语言文件键值表
#include <tchar.h>
#define MTRES_TEXT (TEXT("MTResText"))//配置资源文件中所在节名
#define MTFOLDER_TEXT (TEXT("MTFolderText")) //配置选择文件中所在的节点名
#define MTRES_ADD (TEXT("MTRES_ADD"))//添加资源提示
#define MTRES_VIDEO_PICTURE (TEXT("MTRES_VIDEO_PICTURE")) //视频拍照
#define MTRES_TIP_RESLIST (TEXT("MTRES_TIP_RESLIST"))//切换到资源目录面板按钮提示
#define MTRES_TIP_SCAN (TEXT("MTRES_TIP_SCAN"))//滑动浏览资源提示
#define MTRES_TIP_DRAG (TEXT("MTRES_TIP_DRAG"))//拖拽资源提示
#define MTRES_SWITCH_RES (TEXT("MTRES_SWITCH_RES")) //切换到资源库
#define MTFOLDER_MYCOMPUTER (TEXT("MTFOLDER_MYCOMPUTER"))//我的电脑
#define MTFOLDER_MYDOCUMENT (TEXT("MTFOLDER_MYDOCUMENT"))//我的文档
#define MTFOLDER_DESKTOP (TEXT("MTFOLDER_DESKTOP"))//桌面
#define MTFOLDER_SYSTEM_DISK (TEXT("MTFOLDER_SYSTEM_DISK"))//系统磁盘
#define MTFOLDER_LOCAL_DISK (TEXT("MTFOLDER_LOCAL_DISK"))//本地磁盘
#define MTFOLDER_REMOVABLE_DISK (TEXT("MTFOLDER_REMOVABLE_DISK"))//可移动磁盘
#define MTFOLDER_MYRESOURCE (TEXT("MTFOLDER_MYRESOURCE"))//我的资源
#define MTFOLDER_CANCEL (TEXT("MTFOLDER_CANCEL"))//取消按钮
#define MTFOLDER_OK (TEXT("MTFOLDER_OK"))       //确定按钮
#define MTFOLDER_FILESELECT (TEXT("MTFOLDER_FILESELECT")) //文件选择
#define MTFOLDER_FOLDERSELECT (TEXT("MTFOLDER_FOLDERSELECT")) //文件夹选择
#define MTFOLDER_FOLDERDELTIP (TEXT("MTFOLDER_FOLDERDELTIP")) //确定要删除吗
#define MTFOLDER_CANCELTIP (TEXT("MTFOLDER_CANCELTIP")) //取消提示
#define MTFOLDER_WARNTIP (TEXT("MTFOLDER_WARNTIP")) //警告

