#ifndef __AVMTTYPE_H__
#define __AVMTTYPE_H__


enum{
	AVMT_UDP_P2P=0,
	AVMT_UDP_P2P_ACK,
	AVMT_UDP_RTT,
	AVMT_UDP_RTT_ACK,
	AVMT_UDP_MTU,
	AVMT_UDP_MTU_ACK,
	AVMT_UDP_AUDIO=6,
	AVMT_UDP_VIDEO,
	AVMT_UDP_FILE,
	AVMT_UDP_DESKTOP,
	AVMT_UDP_DATA,

	AVMT_UDP_RTOU_CORE=253,
	AVMT_UDP_STUN=254,
	AVMT_UDP_STUN_ACK=255,
};

enum{
	AVMT_UDP_AUDIO_SOURCE_CONNECT=0,
	AVMT_UDP_AUDIO_SOURCE_CONNECT_ACK,
	AVMT_UDP_AUDIO_SOURCE_DISCONNECT,
	AVMT_UDP_AUDIO_SOURCE_ENABLE,
	AVMT_UDP_AUDIO_SOURCE_ENABLE_ACK,
	AVMT_UDP_AUDIO_SOURCE_DISABLE,
	AVMT_UDP_AUDIO_SOURCE_DISABLE_ACK,
	AVMT_UDP_AUDIO_SOURCE_FRAME,
	AVMT_UDP_AUDIO_SINK_CONNECT,
	AVMT_UDP_AUDIO_SINK_CONNECT_ACK,
	AVMT_UDP_AUDIO_SINK_DISCONNECT,
	AVMT_UDP_AUDIO_SINK_FRAME,
	AVMT_UDP_AUDIO_SINK_ENABLE,
	AVMT_UDP_AUDIO_SINK_ENABLE_ACK,
	AVMT_UDP_AUDIO_SINK_DISABLE,
	AVMT_UDP_AUDIO_SINK_DISABLE_ACK
};

enum{
	AVMT_UDP_VIDEO_SOURCE_CONNECT=0,
	AVMT_UDP_VIDEO_SOURCE_CONNECT_ACK,
	AVMT_UDP_VIDEO_SOURCE_DISCONNECT,
	AVMT_UDP_VIDEO_SOURCE_ENABLE,
	AVMT_UDP_VIDEO_SOURCE_ENABLE_ACK,
	AVMT_UDP_VIDEO_SOURCE_DISABLE,
	AVMT_UDP_VIDEO_SOURCE_DISABLE_ACK,
	AVMT_UDP_VIDEO_SOURCE_FRAME,
	AVMT_UDP_VIDEO_SOURCE_FRAME_ACK,
	AVMT_UDP_VIDEO_SINK_CONNECT,
	AVMT_UDP_VIDEO_SINK_CONNECT_ACK,
	AVMT_UDP_VIDEO_SINK_DISCONNECT,
	AVMT_UDP_VIDEO_SINK_FRAME,
	AVMT_UDP_VIDEO_SINK_FRAME_ACK,
	AVMT_UDP_VIDEO_SINK_ENABLE,
	AVMT_UDP_VIDEO_SINK_ENABLE_ACK,
	AVMT_UDP_VIDEO_SINK_DISABLE,
	AVMT_UDP_VIDEO_SINK_DISABLE_ACK,
	AVMT_UDP_VIDEO_SINK_FRAME_RTP,
	AVMT_UDP_VIDEO_SOURCE_FRAME_RTP,
};

enum{
	AVMT_UDP_FILE_SOURCE_CONNECT=0,
	AVMT_UDP_FILE_SOURCE_CONNECT_ACK,
	AVMT_UDP_FILE_SOURCE_DISCONNECT,
	AVMT_UDP_FILE_SOURCE_FRAME,
	AVMT_UDP_FILE_SOURCE_FRAME_ACK,
	AVMT_UDP_FILE_SINK_CONNECT,
	AVMT_UDP_FILE_SINK_CONNECT_ACK,
	AVMT_UDP_FILE_SINK_DISCONNECT,
	AVMT_UDP_FILE_SINK_FRAME,
	AVMT_UDP_FILE_SINK_FRAME_ACK,
	AVMT_UDP_FILE_KEEP_ALIVE,
	AVMT_UDP_FILE_KEEP_ALIVE_ACK
};


enum{
	AVMT_UDP_DATA_SESSION_CONNECT=0,
	AVMT_UDP_DATA_SESSION_CONNECT_ACK,
	AVMT_UDP_DATA_SESSION_DISCONNECT,
	AVMT_UDP_DATA_SESSION_C2S_FRAME,
	AVMT_UDP_DATA_SESSION_S2C_FRAME,
	AVMT_UDP_DATA_KEEP_ALIVE,
	AVMT_UDP_DATA_KEEP_ALIVE_ACK
};

enum{
	AVMT_UDP_PIPE_SESSION_PARENT_CONNECT=0,
	AVMT_UDP_PIPE_SESSION_PARENT_CONNECT_ACK,
	AVMT_UDP_PIPE_SESSION_PARENT_DISCONNECT,
	AVMT_UDP_PIPE_SESSION_PARENT_C2S_FRAME,
	AVMT_UDP_PIPE_SESSION_PARENT_S2C_FRAME,
	AVMT_UDP_PIPE_SESSION_PARENT_KEEP_ALIVE,
	AVMT_UDP_PIPE_SESSION_PARENT_KEEP_ALIVE_ACK,
	AVMT_UDP_PIPE_SESSION_CHILD_CONNECT,
	AVMT_UDP_PIPE_SESSION_CHILD_CONNECT_ACK,
	AVMT_UDP_PIPE_SESSION_CHILD_DISCONNECT,
	AVMT_UDP_PIPE_SESSION_CHILD_C2S_FRAME,
	AVMT_UDP_PIPE_SESSION_CHILD_S2C_FRAME,
	AVMT_UDP_PIPE_SESSION_CHILD_KEEP_ALIVE,
	AVMT_UDP_PIPE_SESSION_CHILD_KEEP_ALIVE_ACK
};


enum {
	AVMT_VIDEO_ENABLE=0,
	AVMT_VIDEO_DISABLE,
	AVMT_VIDEO_KEYFRAME,
	AVMT_VIDEO_LOST_PACKETS,
	AVMT_VIDEO_REPAIR_PACKETS,
	AVMT_VIDEO_ACK_PACKETS,
	AVMT_VIDEO_PTZ,
	AVMT_VIDEO_CTRL,
	AVMT_VIDEO_FULL_FRAME_RATE,
	AVMT_VIDEO_HALF_FRAME_RATE,
	AVMT_VIDEO_AUTO_FRAME_RATE,
	AVMT_VIDEO_REQUEST_FRAME_TYPE,
};

#define VIDEO_REQUEST_MAIN_FRAME	0x01
#define VIDEO_REQUEST_SUB_FRAME		0x02
#define VIDEO_REQUEST_QSUB_FRAME	0x04

#endif