#ifndef _MTTOUCH_CONNECT_PROTOCOL_TYPE_H_
#define _MTTOUCH_CONNECT_PROTOCOL_TYPE_H_



enum EProtocolType{
	PROTOCOL_WINTOUCH_CONNECT = 0,
	PROTOCOL_HID_CONNECT = 1,
	PROTOCOL_TUIO_CONNECT = 2,
};
#endif


