// DM64Queue.h
//
// Generated by DriverWizard 3.2.0 (Build 2485)
// Requires DDK and DriverWorks
// File created on 9/29/2007
//
// This include file contains the definition of a subclass of KDriverManagedQueueCsq.
// This class implements a driver managed queue that serializes IRP
// processing so that requests are processed one at a time.  Not all
// IRP's are required to use a queue.  More than one instance of this
// queue may be used.  For instance, the driver may be able to process
// reads and writes at the same time (i.e. 2 different channels.)
// This class has the benefit of NOT using the system global cancel
// spin lock.
//
#ifndef __DM64QUEUE_H__
#define __DM64QUEUE_H__

class DM64Queue : public KDriverManagedQueueCsq
{
public:
	SAFE_DESTRUCTORS;
	virtual VOID StartIo(KIrp I);
};

#endif // __DM64QUEUE_H__
