// DM64Driver.h
//
// Generated by DriverWizard 3.2.0 (Build 2485)
// Requires DDK and DriverWorks
// File created on 9/29/2007
//
// This include file contains the definition of a subclass of KDriver.
// WDM drivers declare a subclass of KDriver and override member
// function DriverEntry and AddDevice.
//
#ifndef __DM64DRIVER_H__
#define __DM64DRIVER_H__

class DM64Driver : public KDriver
{
	SAFE_DESTRUCTORS
public:
	// Member functions
	virtual NTSTATUS DriverEntry(PUNICODE_STRING RegistryPath);
	virtual NTSTATUS AddDevice(PDEVICE_OBJECT Pdo);
	virtual VOID Unload(VOID);

protected:
	// Member data
	int		m_Unit;
};

#endif // __DM64DRIVER_H__
