//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Plugin_WB_Main.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDS_ABOUTBOX                    101
#define IDD_AVCONWB_DIALOG              102
#define IDR_MENU1                       128
#define IDB_WBMENU_LOGINFILE            129
#define IDB_WBMENU_LOGOUTFILE           130
#define IDB_WBMENU_NEWFILE              131
#define IDB_WBMENU_OPENFILE             132
#define IDD_WBMAIN_DIALOG               132
#define IDB_WBMENU_SAVEFILE             133
#define IDB_WBMENU_RESAVEFILE           134
#define IDB_WBMENU_PRINTFILE            135
#define IDB_WBMENU_CLOSEFILE            136
#define IDB_WBMENU_NEWPAGE              137
#define IDB_WBMENU_PREPAGE              138
#define IDB_WBMENU_NEXTPAGE             139
#define IDB_WBMENU_SELECTEDIT           140
#define IDB_WBMENU_UNDOEDIT             141
#define IDB_WBMENU_REDOEDIT             142
#define IDB_WBMENU_CLONEEDIT            143
#define IDB_WBMENU_INTINITEEDIT         144
#define IDB_WBMENU_CUTEDIT              145
#define IDB_WBMENU_COPYEDIT             146
#define IDB_WBMENU_PASTEEDIT            147
#define IDB_WBMENU_DELETEEDIT           148
#define IDB_WBMENU_DELETEALLEDIT        149
#define IDB_WBMENU_PRELAYEREDIT         150
#define IDB_WBMENU_NEXTLAYEREDIT        151
#define IDB_WBMENU_TOPLAYEREDIT         152
#define IDB_WBMENU_BOTTOMLAYEREDIT      153
#define IDB_WBMENU_DEASIL45EDIT         154
#define IDB_WBMENU_DEASIL90EDIT         155
#define IDB_WBMENU_WIDDERSHINS45EDIT    156
#define IDB_WBMENU_WIDDERSHINS90EDIT    157
#define IDB_WBMENU_ROTATION180EDIT      158
#define IDB_WBMENU_HIRIZONTALEDIT       159
#define IDB_WBMENU_VERTICALEDIT         160
#define IDB_WBMENU_PICTUREINSERT        161
#define IDB_WBMENU_VEDIOINSERT          162
#define IDB_WBMENU_FLASHINSERT          163
#define IDB_WBMENU_DOCUMENTSINSERT      164
#define IDB_WBMENU_CAMERAHEADSINSERT    165
#define IDB_WBMENU_WRITINGSINSERT       166
#define IDB_WBMENU_ANNOTATIONSINSERT    167
#define IDB_WBMENU_BEELINESDRAW         168
#define IDB_WBMENU_CURVESDRAW           169
#define IDB_WBMENU_RECTDRAW             170
#define IDB_WBMENU_TRIANGLESDRAW        171
#define IDB_WBMENU_ROUNDDRAW            172
#define IDB_WBMENU_RHOMBUSDRAW          173
#define IDB_WBMENU_POLYGONSDRAW         174
#define IDB_WBMENU_BIGRUBBERSDRAW       175
/*#define IDB_WBMENU_LITTERRUBBERSDRAW    176*/
#define IDB_WBMENU_CURVERUBBERSDRAW     177
#define IDB_WBMENU_OBJRUBBERSDRAW       178
#define IDB_WBMENU_BAFFLESTOOL          179
#define IDB_WBMENU_SPOTLIGHTSTOOL       180
#define IDB_WBMENU_MAGNIFIERSTOOL       181
#define IDB_WBMENU_CUTSCREENSTOOL       182
#define IDB_WBMENU_SCREENRECSTOOL       183
#define IDB_WBMENU_DDOTOOL              184
#define IDB_WBMENU_DDESTOOL             185
#define IDB_WBMEETINGROOMNAME           186
#define IDB_WBMEETINGMEMBER_OFFLINE     187
#define IDB_WBMEETINGMEMBER_ONLINE      188
#define IDB_WBNOMEMBERINMEETING         189
#define IDB_WBMENU_RRESOURCELISTSTOOL   190
#define IDB_WBMENU_DDCTOOLL             191
#define IDB_WBMENU_RESOURCEMANAGESTOOL  192
#define IDB_WBMENU_FUNCTIONDLGSTOOL     193
#define IDB_WBMENU_ABOUTHELP            194
#define IDB_WBMENU_HELP                 195
#define IDB_WBMENU_DELETEPAGE           196
#define IDB_WBMENU_FIRSTPAGE            197
#define IDB_WBMENU_INSERTPAGE           198
#define IDB_WBMENU_LASTPAGE             199
#define IDB_WBMENU_RECYCLE              200
#define IDB_WBMEETINGLSTNAME            201
#define IDC_MEETINGLIST                 1001
#define IDC_SERVERADDHOST_EDIT          1005
#define IDC_SINGLELAND_BTN              1006
#define IDC_ONLINE_BTN                  1007
#define IDC_LOGINID_COMBOX              1008
#define IDC_LOGINPASSWORD_EDIT          1009
#define IDC_SHOWLANDMESSAGE_STATIC      1010
#define IDC_CLOSELOGINDLG_BTN           1011
#define IDC_MEMBERLIST_TREE             1013
#define IDC_CANCEL_BTN                  1015
#define IDC_CHECKMTFUNCTION             1016
#define IDD_WBMAINDLG                   2002
#define IDD_WBLOGINDLG                  2003
#define IDD_WHITEBOARD_DLG              2004
#define IDD_MEETINGLIST_DLG             2005
#define IDR_MAINFRAME                   2006
#define IDD_AVCONWBLOGIN_DLG            2007
#define IDI_ICON1                       2010
#define IDI_ICON2                       2011
#define IDC_NEWFILE_BTN                 32772
#define IDC_OPENFILE_BTN                32773
#define IDC_SAVEFILE_BTN                32774
#define IDC_RESAVEFILE_BTN              32775
#define IDC_PRINTFILE_BTN               32776
#define IDC_CLOSEFILE_BTN               32777
#define ID_Menu                         32778
#define IDC_SELECTEDIT_BTN              32779
#define IDC_UNDOEDIT_BTN                32780
#define IDC_REDOEDIT_BTN                32781
#define IDC_CLONEEDIT_BTN               32784
#define ID_Menu32785                    32785
#define IDC_INFINITECLONEEDIT_BTN       32786
#define ID_Menu32787                    32787
#define IDC_CUTEDIT_BTN                 32788
#define IDC_COPYEDIT_BTN                32789
#define IDC_PASTEEDIT_BTN               32790
#define IDC_DELETEEDIT_BTN              32791
#define IDC_DELETEALLEDIT_BTN           32792
#define IDC_PRELAYEREDIT_BTN            32795
#define IDC_NEXTLAYEREDIT_BTN           32796
#define IDC_TOPLAYER_BTN                32797
#define IDC_BOTTOMLAYEREDIT_BTN         32798
#define IDC_DEASIL45EDIT_BTN            32801
#define IDC_DEASIL90EDIT_BTN            32802
#define IDC_WIDDERSHINS90EDIT_BTN       32804
#define IDC_WIDDERSHINS45EDIT_BTN       32805
#define IDC_ROTATION180EDIT_BTN         32806
#define IDC_NEWPAGE_BTN                 32807
#define IDC_PREPAGE_BTN                 32808
#define IDC_NEXTPAGE_BTN                32809
#define IDC_FIRSTPAGE_BTN               32810
#define IDC_LASTPAGE_EDIT               32811
#define IDC_INSERTPAGE_BTN              32812
#define IDC_DELETEPAGE_BTN              32813
#define IDC_MEDIOINSERT_BTN             32818
#define IDC_PICTUREINSERT_BTN           32819
#define IDC_FLASHINSERT_BTN             32820
#define IDC_DOCUMENTINSERT_BTN          32821
#define IDC_CAMERAINSERT_BTN            32823
#define IDC_TEXTINSERT_BTN              32824
#define ID_LOGINPERSON_STATICS          32824
#define IDC_FONTINSERT_BTN              32825
#define IDC_ANNOTATIONSINSERT_BEN       32827
#define IDC_LINEDRAW_BEN                32828
#define IDC_CURVEDRAW_BEN               32829
#define IDC_RECTDRAW_BEN                32832
#define IDC_TRIANGLEDRAW_BEN            32833
#define IDC_ELLIPSEDRAW_BEN             32834
#define IDC_RHOMBUSDRAW_BEN             32836
#define IDC_POLYGONDRAW_BEN             32837
#define IDC_BIGERRUBBERDRAW_BTN         32839
/*#define IDC_SMALLRUBBERDRAW_BEN         32841*/
#define IDC_CURVERUBBERDRAW_BEN         32842
#define IDC_OBJRUBBERDRAW_BTN           32843
#define IDC_BAFFLETOOL_BEN              32844
#define IDC_SPOTLIGHTTOOL_BTN           32845
#define IDC_MAQNTOOL_BTN                32847
#define IDC_CUTSCREENTOOL_BTN           32848
#define IDC_SCREENRECTOOL_BTN           32849
#define IDC_RESOURCETOOL_BTN            32850
//#define IDC_RESOURCEMANAGETOOL_BTN      32851
#define ID_Menu32852                    32852
#define ID_Menu32853                    32853
#define IDC_OPENSCREENDRAWTOOL_BTN      32854
#define IDC_CLOSESCREENDRAWTOOL_BTN     32855
#define IDC_EFFECTSCREENDRAW_BTN        32858
#define IDC_ABOUTHELP_BTN               32859
#define IDC_LOOKHELP_BTN                32860
#define IDC_FUNCTIONTOOL_BTN            32861
#define IDC_ROTATION_HIRIZONTALEDIT_BTN 32863
#define IDC_ROTATION_VERTICALEDIT_BTN   32864
#define IDC_LOAD_BTN                    32865
#define IDC_RECYCLE_BTN                 32866
#define IDC_LOGOUT_BTN                  32867

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2012
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         2004
#define _APS_NEXT_SYMED_VALUE           2002
#endif
#endif
