/* This file was generated by RADVISION ASN.1 Compiler */
/* This is a compilation of : asn_messages\systemConfig.asn, asn_messages\h450config.asn */
/* Command line : ..\asn1\compiler\asn.exe asn_messages\systemConfig.asn asn_messages\h450config.asn -o asn_objects\commonasn -p _common  */

/***********************************************************************
Filename   : asn_objects\commonasn.h
Description: ASN.1 Generated definitions file
************************************************************************
        Copyright (c) 2006 RADVISION Ltd.
************************************************************************
NOTICE:
This document contains information that is confidential and proprietary
to RADVISION Ltd.. No part of this document may be reproduced in any
form whatsoever without written prior approval by RADVISION Ltd..

RADVISION Ltd. reserve the right to revise this publication and make
changes changes without obligation to notify any person of such
revisions or changes.
***********************************************************************/

#ifndef _asn_messages_systemConfig6678924_ASN_H
#define _asn_messages_systemConfig6678924_ASN_H

#include "rvconfig.h"

#ifdef __cplusplus
extern "C" {
#endif

unsigned char* commonasnGetSyntax(void);

#ifdef __cplusplus
#define __ENUM enum
#define __NAME1 _common
#define __NAME2 
#else
#define __ENUM typedef enum
#define __NAME1 
#define __NAME2 _common
#endif


/*lint -save -e793      ANSI limits */
__ENUM __NAME1 {
  _common_CCConfig = 0,
  _common_CDConfig = 10,
  _common_CHConfig = 20,
  _common_CIConfig = 30,
  _common_CMNConfig = 40,
  _common_COConfig = 51,
  _common_CPConfig = 61,
  _common_CTConfig = 71,
  _common_CWConfig = 81,
  _common_H450SystemConfiguration = 91,
  _common_MWIConfig = 116,
  _common_SystemConfiguration = 127,
  _common_TempSystemParams = 148,
  _common_TransportAddress = 166,
  _common_allocations = 184,
  _common_allocations_5 = 197,
  _common_allocations_76 = 212,
  _common_c_default_cipl = 228,
  _common_c_default_cipl_124 = 244,
  _common_callPropertyMode = 264,
  _common_callPropertyMode_33 = 282,
  _common_canRetainService = 303,
  _common_canRetainService_114 = 321,
  _common_cct1 = 343,
  _common_cct1_111 = 349,
  _common_cct2Busy = 359,
  _common_cct2Busy_112 = 369,
  _common_cct2NoResponse = 383,
  _common_cct2NoResponse_113 = 399,
  _common_cdt1 = 419,
  _common_cdt2 = 425,
  _common_cdt3 = 431,
  _common_cdt4 = 437,
  _common_cdt5 = 443,
  _common_chanDescs = 449,
  _common_channels = 460,
  _common_checkParamLength = 470,
  _common_cht1 = 488,
  _common_cht2 = 494,
  _common_cicl = 500,
  _common_cidAssociate = 506,
  _common_cipl = 520,
  _common_cit1 = 526,
  _common_cit2 = 532,
  _common_cit3 = 538,
  _common_cit4 = 544,
  _common_cit5 = 550,
  _common_cit6 = 556,
  _common_classReference = 562,
  _common_cmnt = 578,
  _common_cmnt_126 = 584,
  _common_constrainingField = 594,
  _common_containerOfObjectSets = 613,
  _common_containerOfObjects = 636,
  _common_containerOfTypes = 656,
  _common_containerOfValues = 674,
  _common_copySingleMessages = 693,
  _common_cpt1 = 713,
  _common_cpt10 = 719,
  _common_cpt2 = 726,
  _common_cpt3 = 732,
  _common_cpt4 = 738,
  _common_cpt5 = 744,
  _common_cpt6 = 750,
  _common_cpt7 = 756,
  _common_cpt8 = 762,
  _common_cpt9 = 768,
  _common_ctt1 = 774,
  _common_ctt2 = 780,
  _common_ctt3 = 786,
  _common_ctt4 = 792,
  _common_defaultScopeId = 798,
  _common_defaultScopeId_30 = 814,
  _common_deleteSingleMessages = 833,
  _common_delimiter = 855,
  _common_delimiter_4 = 866,
  _common_dnsDomains = 879,
  _common_dnsDomains_73 = 891,
  _common_dnsDomains_73_74 = 906,
  _common_dnsMaxBuffSize = 924,
  _common_dnsMaxDomains = 940,
  _common_dnsMaxQueries = 955,
  _common_dnsMaxServers = 970,
  _common_dnsQueryBuffSize = 985,
  _common_dnsRetries = 1003,
  _common_dnsRetries_71 = 1015,
  _common_dnsServers = 1030,
  _common_dnsServers_72 = 1042,
  _common_dnsSupported = 1057,
  _common_dnsTimeOut = 1071,
  _common_dnsTimeOut_70 = 1083,
  _common_doNotUseProperty = 1098,
  _common_extraConnections = 1116,
  _common_fieldOfClassReference = 1134,
  _common_fieldOfEnumerated = 1157,
  _common_fieldOfObjectReference = 1176,
  _common_fieldReference = 1200,
  _common_fullProperty = 1216,
  _common_gkInNat = 1230,
  _common_imports = 1239,
  _common_importsArray = 1248,
  _common_indicateCalling = 1262,
  _common_interval = 1279,
  _common_ip = 1289,
  _common_ip6Address = 1293,
  _common_ip6Address_60 = 1305,
  _common_ipAddress = 1320,
  _common_ipAddress_45 = 1331,
  _common_ipSourceRoute = 1345,
  _common_ipSourceRoute_48 = 1360,
  _common_ipxAddress = 1378,
  _common_ipxAddress_56 = 1390,
  _common_localAddress = 1405,
  _common_localIPAddress = 1419,
  _common_loose = 1435,
  _common_manualStart = 1442,
  _common_maxBuffSize = 1455,
  _common_maxCalls = 1468,
  _common_maxChannels = 1478,
  _common_maxMultiHomedAddresses = 1491,
  _common_maxMultiHomedAddresses_20 = 1515,
  _common_maxPoolSizeInKB = 1542,
  _common_maxPoolSizeInKB_18 = 1559,
  _common_maxProcs = 1579,
  _common_maxRasInTransactions = 1589,
  _common_maxRasOutTransactions = 1611,
  _common_maxServices = 1634,
  _common_maxServices_84 = 1647,
  _common_maxTcpUnit = 1663,
  _common_messages = 1675,
  _common_module = 1685,
  _common_mwit1 = 1693,
  _common_mwit2 = 1700,
  _common_nameChans = 1707,
  _common_natMode = 1718,
  _common_natModeNAT = 1727,
  _common_natModeNoNAT = 1739,
  _common_natModeOnlyNAT = 1753,
  _common_natMode_65 = 1769,
  _common_netBios = 1781,
  _common_netBios_63 = 1790,
  _common_netnum = 1802,
  _common_netnum_58 = 1810,
  _common_node = 1821,
  _common_node_57 = 1827,
  _common_nsap = 1836,
  _common_nsap_64 = 1842,
  _common_objectArray = 1851,
  _common_objectReference = 1864,
  _common_objectSetArray = 1881,
  _common_objectSetElement = 1897,
  _common_objectSetReference = 1915,
  _common_pdlName = 1935,
  _common_pdlName_75 = 1944,
  _common_port = 1956,
  _common_portFrom = 1962,
  _common_portTo = 1972,
  _common_port_59 = 1980,
  _common_protocols = 1989,
  _common_route = 2000,
  _common_route_51 = 2007,
  _common_routing = 2017,
  _common_routing_53 = 2026,
  _common_silentMonitorInd = 2038,
  _common_silentMonitorInd_125 = 2056,
  _common_strict = 2078,
  _common_supportEFC = 2086,
  _common_tcw = 2098,
  _common_tempSystemParams = 2103,
  _common_tpktChans = 2121,
  _common_tpktNoBuffers = 2132,
  _common_typeArray = 2147,
  _common_typeFromConstraint = 2158,
  _common_typeReference = 2178,
  _common_udpChans = 2193,
  _common_valueNode = 2203,
  _common_valueTree = 2214,
  _common_values = 2225,
  _common_vtNodeCount = 2233,
  _common_vtPoolSize = 2246,
  _common_watchdog = 2258,
  _common_watchdog_38 = 2268,
  _common_withSyntaxElement = 2281} __NAME2;


/*lint -restore */
#undef __NAME1
#undef __NAME2
#undef __ENUM

#define _common(a) ((RvPstFieldId)_common_##a),
#define __common(a) ((RvPstFieldId)_common_##a)

#ifdef __cplusplus
}
#endif

#endif /* _asn_messages_systemConfig6678924_ASN_H */
