/*++

Copyright(R) 2010 AVCON. All rights reserved.

file:
	AH3K.h

remark:
	设备接口和IOCTLs
	本头文件提供给调用者

author:
	feichao

time:
	<time>

revision:
	0000 <revision description>

--*/
#ifndef __AH3K_H__
#define __AH3K_H__


#include <initguid.h>


// {D2CECC7E-6AD4-44f8-867E-F5310C1EFD09}
DEFINE_GUID(GUID_DEVICE_AH3K, 
0xd2cecc7e, 0x6ad4, 0x44f8, 0x86, 0x7e, 0xf5, 0x31, 0xc, 0x1e, 0xfd, 0x9);



#define FILE_DEVICE_AH3K  0x8000


#define IOCTL_BASE 0x900


//
//寄存器
//
typedef struct _AH3K_REG
{
	ULONG Address;
	ULONG Value;
}AH3K_REG,*PAH3K_REG;



//REG READ
#define IOCTL_AH3K_REG_READ \
	CTL_CODE(FILE_DEVICE_AH3K, IOCTL_BASE +10, METHOD_BUFFERED, FILE_ANY_ACCESS)

//REG WRITE
#define IOCTL_AH3K_REG_WRITE \
	CTL_CODE(FILE_DEVICE_AH3K, IOCTL_BASE +11, METHOD_BUFFERED, FILE_ANY_ACCESS)


//
//Memory
//
typedef struct _AH3K_MEM
{
	ULONG Address;
	ULONG Length;
}AH3K_MEM,*PAH3K_MEM;

//MEM READ
#define IOCTL_AH3K_MEM_READ \
	CTL_CODE(FILE_DEVICE_AH3K, IOCTL_BASE +12, METHOD_BUFFERED, FILE_ANY_ACCESS)

//MEM WRITE
#define IOCTL_AH3K_MEM_WRITE \
	CTL_CODE(FILE_DEVICE_AH3K, IOCTL_BASE +13, METHOD_BUFFERED, FILE_ANY_ACCESS)


//DSP RESET
#define IOCTL_AH3K_DSP_RESET \
	CTL_CODE(FILE_DEVICE_AH3K, IOCTL_BASE +14, METHOD_BUFFERED, FILE_ANY_ACCESS)

//DSP RUN
#define IOCTL_AH3K_DSP_RUN \
	CTL_CODE(FILE_DEVICE_AH3K, IOCTL_BASE +15, METHOD_BUFFERED, FILE_ANY_ACCESS)



typedef struct _AH3K_FIRMWIRE
{
	DWORD Version;
	DWORD GBLCTL;
	DWORD CECTL1;
	DWORD CECTL0;
	DWORD CECTL2;
	DWORD CECTL3;
	DWORD SDCTL;
	DWORD SDTIM;
	DWORD SDEXT;
	DWORD PDTCTL;
	DWORD CESEC1;
	DWORD CESEC0;
	DWORD CESEC2;
	DWORD CESEC3;

	ULONG CoffLength;

}AH3K_FIRMWIRE,*PAH3K_FIRMWIRE;


//DSP LOAD
#define IOCTL_AH3K_DSP_LOAD \
	CTL_CODE(FILE_DEVICE_AH3K, IOCTL_BASE +16, METHOD_BUFFERED, FILE_ANY_ACCESS)



//DSP CMD
#define IOCTL_AH3K_DSP_CMD \
	CTL_CODE(FILE_DEVICE_AH3K, IOCTL_BASE +17, METHOD_BUFFERED, FILE_ANY_ACCESS)


#define AH3K_CMD_MEGIC	'v101'
#define AH3K_CMD_VIDEOCAP_STATE_SET 1


//DSP MSG
#define IOCTL_AH3K_DSP_MSG \
	CTL_CODE(FILE_DEVICE_AH3K, IOCTL_BASE +18, METHOD_BUFFERED, FILE_ANY_ACCESS)


// 通讯结构

//PC到DSP的消息包
typedef struct _MSG_PACKET
{
	UCHAR enable;	
	UCHAR scale_type;
	UCHAR framerate;
	UCHAR channel_index;

	USHORT width;
	USHORT height;
}MSG_PACKET,*PMSG_PACKET;





#define PORT_TYPE_CVBS		0
#define PORT_TYPE_DVI		1
#define PORT_TYPE_HDMI		2
#define PORT_TYPE_SDI		3
#define PORT_TYPE_SVIDEO	4
#define PORT_TYPE_VGA		5


#define BITRATE_CBR			0
#define BITRATE_VBR 		1

#define FRAME_VERSION		0x01

#define FRAME_AUDIO			0
#define FRAME_I				1
#define FRAME_P				2
#define FRAME_VIDEO			4
#define FRAME_NULL			8

typedef struct _DAT_PACKET
{
	union
	{
		struct{
			UCHAR version;
			UCHAR frame_type;
			UCHAR channel;
			UCHAR framerate;
		}byte;

		ULONG all;
	}Base;

	USHORT nOutputWidth;
	USHORT nOutputHeight;

	USHORT nInputWidth;
	USHORT nInputHeight;

	UCHAR nInputFrameRate;
	UCHAR nPortType;
	USHORT nReserved;

}DAT_PACKET,*PDAT_PACKET;


//PROPERTY GET
//typedef struct _AH3K_PROPERTY
//{
//	ULONG PortCount;
//
//}AH3K_PROPERTY,PAH3K_PROPERTY;
//
//#define IOCTL_AH3K_PROPERTY_GET \
//	CTL_CODE(FILE_DEVICE_AH3K, IOCTL_BASE +18, METHOD_BUFFERED, FILE_ANY_ACCESS)
//
//
//
//

//PORTTYPE

#define TYPE_AUDIO			1
#define TYPE_VIDEO_DVII		2
#define TYPE_VIDEO_DSUB		3
#define TYPE_VIDEO_HDMI		4
#define TYPE_VIDEO_CVBS		5
#define TYPE_VIDEO_SDI		6
	

#define IOCTL_AH3K_PORTTYPE_GET \
	CTL_CODE(FILE_DEVICE_AH3K, IOCTL_BASE +20, METHOD_BUFFERED, FILE_ANY_ACCESS)
//
//
//
//


#endif