
#ifndef VIDEC_VERSION_H
#define VIDEC_VERSION_H


#define VIDEC_FILEVERSION_ONE			1
#define VIDEC_FILEVERSION_TWO			7
#define VIDEC_FILEVERSION_THREE			2

#define VIDEC_FILEVERSION_FOUR			302

#define VIDEC_FILEVERSION_STR       "1.7.2.20160302"



#endif // VIDEC_VERSION_H
