/***********************************************************************
        Copyright (c) 2002 RADVISION Ltd.
************************************************************************
NOTICE:
This document contains information that is confidential and proprietary
to RADVISION Ltd.. No part of this document may be reproduced in any
form whatsoever without written prior approval by RADVISION Ltd..

RADVISION Ltd. reserve the right to revise this publication and make
changes without obligation to notify any person of such revisions or
changes.
***********************************************************************/

#ifndef _TRANSPORT_H
#define _TRANSPORT_H

/*************************************************************************************
 * Transport module
 * ----------------
 *
 * This is the module that interacts with the network on one hand, while on the other
 * it communicates with the other protocol modules, such as Q.931, H.245, H.450 etc.
 *
 * The lower level can handle TPKT, Annex E types of communications in a transparent
 * way to th eupper layers.
 *
 * The upper level exports and imports (by means of APIs and callbacks) messages to the
 * different modules: Mainly Q.931, H.245 (including tunneled messages) and the
 * rest of the tunneled protocols (Annex M, Annex L).
 *
 **************************************************************************************/

#include "rvinternal.h"
#include "rvh323connection.h"
#include "pvaltree.h"

#ifdef __cplusplus
extern "C" {
#endif


/* Handle to the instance of the transport module, generated by init */
RV_DECLARE_HANDLE(HAPPTRANS);

/* Application Handle to the instance of the transport module, generated by init */
RV_DECLARE_HANDLE(HAPPATRANS);

/* Stack internal handle to a session */
RV_DECLARE_HANDLE(HSTRANSSESSION);

/* Application handle to a session, in most cases will be the call handle
   associated with that session */
RV_DECLARE_HANDLE(HATRANSSESSION);

/* Stack internal host handle, used to identify a specific host connection. */
RV_DECLARE_HANDLE(HSTRANSHOST);

/* Application host handle. */
RV_DECLARE_HANDLE(HATRANSHOST);


/* Error codes that can be returned by the module's API and callbacks */
typedef enum {
        cmTransErrNoParty = -2,     /* There is no party to connect with */
        cmTransErr = -1,            /* general error */
        cmTransOK,                  /* All is ok */
        cmTransConnectionClosed,    /* The connection no longer active */
        cmTransConnectionBusy,      /* The connection is still sending previous messages */
        cmTransHostNotMultiplexed,  /* A non multiplexed host was used fr more than one session */
        cmTransWouldBlock,          /* not enough buffers for send/receive */
        cmTransIgnoreMessage,       /* Ignore the message and stop process it (may be set by H.235) */
        cmTransDummyHost            /* Message not really sent, because host is Dummy Control */
} TRANSERR;

/* Types of messages */
typedef enum {
    cmTransQ931Type,
    cmTransH245Type,
    cmTransAnnexLType,
    cmTransAnnexMType
} TRANSTYPE;

/* Types of connection */
typedef enum {
    cmTransQ931Conn,
    cmTransH245Conn
} TRANSCONNTYPE;

/* The parameters that each session may have */
typedef enum {
    cmTransParam_host,                          /* What host connection is associated with
                                                   the session (in multiplexing several
                                                   sessions may have the same host connection) */
    cmTransParam_H245Connection,                /* The host used to establish the H.245 connection
                                                    (read only param) */
    cmTransParam_isTunnelingSupported,          /* Do we support tunneling for the session */
    cmTransParam_notEstablishControl,           /* Don't open an H.245 connection */
    cmTransParam_H245Stage,                     /* when is it allowed to send the H.245 address */
    cmTransParam_isParallelTunnelingSupported,  /* Is it allowed to have both FastStart and
                                                   tunneling on the same call */
    cmTransParam_shutdownEmptyConnection,       /* Should the host connection associated with this
                                                   session be closed when it has no more
                                                   sessions attached to it (multiplexing param) */
    cmTransParam_isMultiplexed,                 /* Does the host connection associated with this
                                                   session supports multiplexing */
    cmTransParam_annexEMode,                    /* Do we support annex E for this session
                                                   (yes/no/maybe)*/
    cmTransParam_sourceIpAddress,               /* The address from which to connect, to be used
                                                   when more than one network interface is aveliable */
    cmTransParam_callTerminating,               /* prevents sending of tunneling facility when set to
                                                   RV_TRUE*/
    cmTransParam_extFastConnect,                /* sets EFC flags in messages */
    cmTransParam_callSupportNat,                /* RV_TRUE if local addresses need NAT translation*/
    cmTransParam_parallelBeforeFS               /* Allows sending of parallel H.245 reply before FS
                                                   when set to RV_TRUE*/
} TRANSSESSIONPARAM;

/* The parameters that each session may have */
typedef enum
{
    cmTransHostParam_shutdownEmptyConnection,   /* Should the host connection be closed when
                                                   it has no more sessions attached to
                                                   it (multiplexing param) */
    cmTransHostParam_isMultiplexed,             /* Does the host connection supports multiplexing */
    cmTransHostParam_remoteAddress,             /* What is the Q.931 address */
    cmTransHostParam_localAddress,              /* what is out local address for Q.931 */
    cmTransHostParam_localAddressInMsg,         /* what is out local address in the Q931 message*/

    cmTransHostParam_annexEMode,                /* Do we support annex E on this host */
    cmTransHostParam_socketBestFit,             /* The connection pointer that is most likely to be used */
    cmTransHostParam_socketConnection,          /* The connection pointer */
    cmTransHostParam_socketh245Listen,          /* The connection pointer for h245 Listening */
    cmTransHostParam_callSupportNat,            /* RV_TRUE if local addresses need NAT translation*/
    cmTransHostParam_firstCall                  /* the first call pointed to by the host */
} TRANSHOSTPARAM;


typedef struct
{
    RvUint32 useAnnexE;
    RvUint32 t_R1;
    RvUint32 t_R2;
    RvUint32 n_R1;
    RvUint32 t_IMA1;
    RvUint32 n_IMA1;
    RvUint32 t_DT;
} CMTRANSANNEXEPARAM;


/**************************************************************************************/
/* Session related callbacks that are used by the transport module */
/**************************************************************************************/

typedef
/**************************************************************************************
 * cmEvTransNewSession (CALLBACK)
 *
 * Purpose: To report to the user that a new session was created due to a new
 *          incoming message. This callback is called only when a new message actually
 *          arrives and not when the connection is established.
 *
 * Input:   hsTrans         - The stack handle of the instance.
 *          haTrans         - The application handle of the instance.
 *          hsTransSession  - The stack handle of the session.
 *          pvtNode         - the node of the SETUP message that caused the creation.
 *
 * Output:  haTransSession  - The application handle of the session.
 *          cause           - In case of rejection, the cause (as in RELEASE COMPLETE).
 *          reasonNameId    - In case of rejection, the reason name Id (as in RELEASE COMPLETE).
 *          manualRAS       - If the appliaction is working in manual RAS mode.
 *
 **************************************************************************************/
    TRANSERR (*cmEvTransNewSessionT)(   IN  HAPPTRANS        hsTrans,
                                        IN  HAPPATRANS       haTrans,
                                        IN  HSTRANSSESSION   hsTransSession,
                                        OUT HATRANSSESSION   *haTransSession,
                                        IN  int              pvtNode,
                                        OUT int              *cause,
                                        OUT RvPstFieldId     *reasonNameId);

typedef
/**************************************************************************************
 * cmEvTransConnectionOnSessionClosed (CALLBACK)
 *
 * Purpose: To report to the user that a session was closed, either normally (i.e.
 *          by the other end) or abnormaly due to connection errors.
 *
 * Input:   hsTransSession - The stack handle of the session.
 *          haTransSession - The application handle of the session.
 *          type           - The connection type.
 *
 **************************************************************************************/
    TRANSERR (*cmEvTransConnectionOnSessionClosedT)(IN HSTRANSSESSION hsTransSession,
                                                    IN HATRANSSESSION haTransSession,
                                                    IN TRANSCONNTYPE  type);


typedef
/**************************************************************************************
 * cmEvTransSessionNewConnection (CALLBACK)
 *
 * Purpose: To report to the user that a a new connection was opened
 *          for the given session.
 *
 * Input:   hsTransSession - The stack handle of the session.
 *          haTransSession - The application handle of the session.
 *          type           - The type of the connection (Q.931 or H.245)
 *
 **************************************************************************************/
    TRANSERR (*cmEvTransSessionNewConnectionT)( IN HSTRANSSESSION   hsTransSession,
                                                IN HATRANSSESSION   haTransSession,
                                                IN TRANSCONNTYPE    type);


typedef
/**************************************************************************************
 * cmEvTransNewMessage (CALLBACK)
 *
 * Purpose: To report to the user that a new message arrived for a session.
 *
 * Input:   hsTransSession - The stack handle of the session.
 *          haTransSession - The application handle of the session.
 *          type           - The type of the message (Q.931/H.245).
 *          pvtNode        - The pvt node of the decoded message.
 *          hMsgContext    - External context associated with the message.
 *
 **************************************************************************************/
    TRANSERR (*cmEvTransNewMessageT)(IN HSTRANSSESSION          hsTransSession,
                                     IN HATRANSSESSION          haTransSession,
                                     IN RvH323ConnectionType    type,
                                     IN int                     pvtNode,
                                     IN void                    *hMsgContext,
                                     IN RvBool                  isTunnelled,
                                     IN int                     index);

typedef
/**************************************************************************************
 * cmEvTransWrite (CALLBACK)
 *
 * Purpose: To report to the user that new buffers are available and that a send operation
 *          may continue successfully.
 *
 * Input:   hsTransSession - The stack handle of the session which previously was pending.
 *          haTransSession - The application handle of the session.
 *
 **************************************************************************************/
    TRANSERR (*cmEvTransWriteT)(IN HSTRANSSESSION hsTransSession,
                                IN HATRANSSESSION haTransSession );


typedef
/**************************************************************************************
 * cmEvTransBadMessage (CALLBACK)
 *
 * Purpose: To report to the user that a message for a session could not be decoded
 *          or encoded.
 *
 * Input:   hsTransSession  - The stack handle of the session.
 *          haTransSession  - The application handle of the session.
 *          type            - The type of the message (Q.931/H.245).
 *          msg             - The encoded message
 *          msgSize         - The encoded message size
 *          outgoing        - RV_TRUE: outgoing message, RV_FALSE-incoming message
 *
 **************************************************************************************/
    TRANSERR (*cmEvTransBadMessageT)(IN HSTRANSSESSION          hsTransSession,
                                     IN HATRANSSESSION          haTransSession,
                                     IN RvH323ConnectionType    type,
                                     RvUint8*                   msg,
                                     int                        msgSize,
                                     RvBool                     outgoing);

typedef
/**************************************************************************************
 * cmEvTransGetMessageNode (CALLBACK)
 *
 * Purpose: To ask the user to give a node id to a skeleton of the requested message.
 *
 * Input:   hPvt    - handle to the pvt we are using
 *          msgType - The type of the message we need.
 *
 * Output:  nodeId  - node id (read-only, do not modify) of the requested message.
 *
 **************************************************************************************/
    TRANSERR (*cmEvTransGetMessageNodeT)(IN  HAPPATRANS         hAppATrans,
                                         IN  cmCallQ931MsgType  msgType,
                                         OUT int                *nodeId);

typedef
/**************************************************************************************
 * cmEvTransNewH450Message (CALLBACK)
 *
 * Purpose: To report to the user that an H.450 message was just received.
 *
 * Input:   hsTransSession  - The stack handle of the session.
 *          haTransSession  - The application handle of the session.
 *          msg             - The encoded message
 *          msgSize         - The encoded message size
 *          msgType         - The type of the message from which tunneled msgs came.
 *
 **************************************************************************************/
    TRANSERR (*cmEvTransNewH450MessageT)(IN HSTRANSSESSION  hsTransSession,
                                         IN HATRANSSESSION  haTransSession,
                                         IN int             msg,
                                         IN int             msgSize,
                                         IN int             msgType);
typedef
/**************************************************************************************
 * cmEvTransNewAnnexMMessage (CALLBACK)
 *
 * Purpose: To report to the user that an Annex M message was just received.
 *
 * Input:   hsTransSession      - The stack handle of the session.
 *          haTransSession      - The application handle of the session.
 *          annexMElement       - The node id of the annex M element of tunneling
 *          msgType         - The type of the message from which tunneled msgs came.
 *
 **************************************************************************************/
    TRANSERR (*cmEvTransNewAnnexMMessageT)(IN HSTRANSSESSION    hsTransSession,
                                           IN HATRANSSESSION    haTransSession,
                                           IN int               annexMElement,
                                           IN int               msgType);

typedef
/**************************************************************************************
 * cmEvTransNewAnnexLMessage (CALLBACK)
 *
 * Purpose: To report to the user that an Annex M message was just received.
 *
 * Input:   hsTransSession      - The stack handle of the session.
 *          haTransSession      - The application handle of the session.
 *          annexLElement       - The node id of the annex L element of tunneling
 *          msgType         - The type of the message from which tunneled msgs came.
 *
 **************************************************************************************/
    TRANSERR (*cmEvTransNewAnnexLMessageT)(IN HSTRANSSESSION    hsTransSession,
                                           IN HATRANSSESSION    haTransSession,
                                           IN int               annexLElement,
                                           IN int               msgType);

typedef
/**************************************************************************************
 * cmEvTransWantsToStartControlT (CALLBACK)
 *
 * Purpose: To ask the CM if it is ok to connect control or send tunneled H.245
 *          messages. (will return RV_FALSE if the GK has not approved the call yet)
 *
 * Input:   hsTransSession      - The stack handle of the session.
 *          haTransSession      - The application handle of the session.
 *
 **************************************************************************************/
    RvBool (*cmEvTransWantsToStartControlT)(IN HSTRANSSESSION    hsTransSession,
                                            IN HATRANSSESSION    haTransSession);

typedef
/**************************************************************************************
 * cmEvTunnelingWasRejectedT (CALLBACK)
 *
 * Purpose: To let the CM know that tunneling was rejected, and that the sent TCS/MSD
 *          messages will not be receiving acknowledgement soon.
 *
 * Input:   hsTransSession      - The stack handle of the session.
 *          haTransSession      - The application handle of the session.
 *
 **************************************************************************************/
    TRANSERR (*cmEvTransTunnelingWasRejectedT)(IN HSTRANSSESSION    hsTransSession,
                                               IN HATRANSSESSION    haTransSession,
                                               IN RvBool            restartTimers);

typedef enum
{
    efcNo = 0,
    efcDesire = 1,
    efcRequire = 2
} EFCSTATE;

typedef
/**************************************************************************************
 * cmEvTransExtFastConnestStateT (CALLBACK)
 *
 * Purpose: To let the CM know which EFC state was requested by the other side.
 *
 * Input:   hsTransSession      - The stack handle of the session.
 *          haTransSession      - The application handle of the session.
 *          efcState            - The other side's EFC state
 *
 **************************************************************************************/
    TRANSERR (*cmEvTransExtFastConnestStateT)(IN HSTRANSSESSION     hsTransSession,
                                              IN HATRANSSESSION     haTransSession,
                                              IN EFCSTATE           efcState);

typedef
/**************************************************************************************
 * cmEvTransNatAddressTranslation (CALLBACK)
 *
 * Purpose: To let the CM know that a NAT translation is needed.
 *
 * Input:   hsTransSession      - The stack handle of the session.
 *          haTransSession      - The application handle of the session.
 *          addressType         - The address type (ras , q931 or h245)
 *          address             - The local address to translate.
 * Output:  address             - The NAT translation for the local address.
 **************************************************************************************/
    TRANSERR (*cmEvTransNatAddressTranslationT) (IN     HSTRANSSESSION      hsTransSession,
                                                IN      HATRANSSESSION      haTransSession,
                                                IN      int                 addrType,
                                                INOUT   cmTransportAddress* address);

typedef
/**************************************************************************************
 * cmEvTransParentChangedT (CALLBACK)
 *
 * Purpose: To change the parent lock of the call to that of the session.
 *
 * Input:   hsTransSession      - The stack handle of the session.
 *          haTransSession      - The application handle of the session.
 *
 **************************************************************************************/
    TRANSERR (*cmEvTransParentChangedT) (IN    HSTRANSSESSION      hsTransSession,
                                         IN    HATRANSSESSION      haTransSession);


typedef
/**************************************************************************************
 * cmEvTransAltEpConnectionT (CALLBACK)
 *
 * Purpose: TBD
 *
 * Input:   hsTransSession      - The stack handle of the session.
 *          haTransSession      - The application handle of the session.
 *
 **************************************************************************************/
    TRANSERR (*cmEvTransAltEpConnectionT)(IN HSTRANSSESSION    hsTransSession,
                                          IN HATRANSSESSION    haTransSession);


typedef  struct
{
    cmEvTransNewSessionT                    cmEvTransNewSession;
    cmEvTransConnectionOnSessionClosedT     cmEvTransConnectionOnSessionClosed;
    cmEvTransSessionNewConnectionT          cmEvTransSessionNewConnection;
    cmEvTransNewMessageT                    cmEvTransNewMessage;
    cmEvTransWriteT                         cmEvTransWrite;
    cmEvTransBadMessageT                    cmEvTransBadMessage;
    cmEvTransGetMessageNodeT                cmEvTransGetMessageNode;
    cmEvTransNewH450MessageT                cmEvTransNewH450Message;
    cmEvTransNewAnnexMMessageT              cmEvTransNewAnnexMMessage;
    cmEvTransNewAnnexLMessageT              cmEvTransNewAnnexLMessage;
    cmEvTransWantsToStartControlT           cmEvTransWantsToStartControl;
    cmEvTransTunnelingWasRejectedT          cmEvTransTunnelingWasRejected;
    cmEvTransExtFastConnestStateT           cmEvTransExtFastConnestState;
    cmEvTransNatAddressTranslationT         cmEvTransNatAddressTranslation;
    cmEvTransParentChangedT                 cmEvTransParentChanged;
    cmEvTransAltEpConnectionT               cmEvTransAltEpConnection;
} TRANSSESSIONEVENTS;

/**************************************************************************************/
/* Host related callbacks that are used by the transport module */
/**************************************************************************************/

typedef
/**************************************************************************************
 * cmEvTransHostConnected (CALLBACK)
 *
 * Purpose: To report to the user that a new host connection was established., and what
 *          kind of connection it is.
 *
 * Input:   hsTransHost - The stack handle of the host.
 *          haTransHost - The application handle of host.
 *          type        - The type of the connection (Q.931/H.245).
 *          isOutgoing  - RV_TRUE for outgoing (connected),RV_FALSE for incoming (accepted)
 *
 **************************************************************************************/
    TRANSERR (*cmEvTransHostConnectedT)(IN HSTRANSHOST   hsTransHost,
                                        IN HATRANSHOST   haTransHost,
                                        IN TRANSCONNTYPE type,
                                        IN RvBool        isOutgoing);


typedef
/**************************************************************************************
 * cmEvTransHostClosed (CALLBACK)
 *
 * Purpose: To report to the user that a host connection was closed, either normally (i.e.
 *          by the other end) or abnormaly due to errors.
 *
 * Input:   hsTransHost  - The stack handle of the host.
 *          haTransHost  - The application handle of the host.
 *          wasConnected - RV_TRUE:  The host was connected before it was closed
 *                         RV_FALSE: The host never reached connection before it was closed.
 *
 **************************************************************************************/
    TRANSERR (*cmEvTransHostClosedT)(   IN HSTRANSHOST hsTransHost,
                                        IN HATRANSHOST haTransHost,
                                        IN RvBool      wasConnected);

typedef
/**************************************************************************************
 * cmEvTransNewRawMessage (CALLBACK)
 *
 * Purpose: To report to the user that an encoded message was just received on the
 *          host connection.
 *
 * Input:   hsTransHost     - The stack handle of the host.
 *          haTransHost     - The application handle of the host.
 *          type            - The type of the message (Q.931, H.245)
 *          pvtNode         - see output params
 *          msg             - The encoded message
 *          msgSize         - The encoded message size
 *          decoded         - see output params
 *          pvtNode         - The root pvt of the message for decoding.
 *
 * Output:  pvtNode         - The pvt tree of the message after decoding.
 *          decoded         - The number of bytes that were decoded
 *          hMsgContext     - external context associated with the message
 *
 **************************************************************************************/
    TRANSERR (*cmEvTransNewRawMessageT)(IN  HSTRANSHOST             hsTransHost,
                                        IN  HATRANSHOST             haTransHost,
                                        IN  RvH323ConnectionType    type,
                                        INOUT int                   pvtNode,
                                        IN  RvUint8*                msg,
                                        IN  int                     msgSize,
                                        OUT int*                    decoded,
                                        OUT void**                  hMsgContext);

typedef
/**************************************************************************************
 * cmEvTransSendRawMessage (CALLBACK)
 *
 * Purpose: To report to the user that a decoded message is about to be sent on
 *          the host connection.
 *
 * Input:   hsTransHost     - The stack handle of the host.
 *          haTransHost     - The application handle of the host.
 *          hsSession       - The stack handle of the session who sent the message.
 *          haSession       - The application handle of the above session.
 *          pvtNode         - The pvt tree of the decoded message.
 *          size            - The maximal size of the given message.
 *
 * Output:  msg             - The message after encoding.
 *          msgSize         - The encoded message size.
 *
 *
 **************************************************************************************/
    TRANSERR (*cmEvTransSendRawMessageT)(   IN  HSTRANSHOST     hsTransHost,
                                            IN  HATRANSHOST     haTransHost,
                                            IN  HSTRANSSESSION  hsSession,
                                            IN  HATRANSSESSION  haSession,
                                            IN  int             pvtNode,
                                            IN  int             size,
                                            OUT RvUint8         *msg,
                                            OUT int             *msgSize);

typedef
/**************************************************************************************
 * cmEvTransHostNewMessage (CALLBACK)
 *
 * Purpose: To report to the user that a new message arrived for a host.
 *
 * Input:   hsTransHost - The stack handle of the host.
 *          haTransHost - The application handle of the host.
 *          type        - The type of the message (Q.931/H.245).
 *          pvtNode     - The pvt node of the decoded message.
 *          hMsgContext - External context associated with the message.
 *
 **************************************************************************************/
    TRANSERR (*cmEvTransHostNewMessageT)(IN HSTRANSHOST hsTransHost,
                                         IN HATRANSHOST haTransHost,
                                         IN TRANSTYPE   type,
                                         IN int         pvtNode,
                                         IN void        *hMsgContext);

typedef
/**************************************************************************************
 * cmEvTransHostBadMessage (CALLBACK)
 *
 * Purpose: To report to the user that a message from a host could not be decoded.
 *
 * Input:   hsTransHost - The stack handle of the host.
 *          haTransHost - The application handle of the host.
 *          type        - The type of the message (Q.931/H.245).
 *          msg             - The encoded message
 *          msgSize         - The encoded message size
 *          outgoing        - RV_TRUE: outgoing message; RV_FALSE-incoming message
 *          hMsgContext  - An external context associated with the message.
 *
 *
 **************************************************************************************/
    TRANSERR (*cmEvTransHostBadMessageT)(IN HSTRANSHOST hsTransHost,
                                         IN HATRANSHOST haTransHost,
                                         IN TRANSTYPE   type,
                                         IN RvUint8     *msg,
                                         IN int         msgSize,
                                         RvBool         outgoing,
                                         void           *hMsgContext);
typedef
/**************************************************************************************
 * cmEvTransHostMultiplexChangeState (CALLBACK)
 *
 * Purpose: To report to the user that a message from a host could not be decoded.
 *
 * Input:   hsTransHost - The stack handle of the host.
 *          haTransHost - The application handle of the host.
 *          type        - The type of the message (Q.931/H.245).
 *          msg             - The encoded message
 *          msgSize         - The encoded message size
 *          outgoing        - RV_TRUE: outgoing message; RV_FALSE-incoming message
 *          hMsgContext  - An external context associated with the message.
 *
 *
 **************************************************************************************/
    TRANSERR (*cmEvTransHostMultiplexChangeStateT)(IN HSTRANSHOST hsTransHost,
                                                   IN HATRANSHOST haTransHost,
                                                   IN RvBool      multiplexOn);

typedef
/**************************************************************************************
 * cmEvTransHostListen (CALLBACK)
 *
 * Purpose: To report to the user that we are about to listen to TCP connections
 *
 *
 * Input:   hsTransHost - The stack handle of the host.
 *          haTransHost - The application handle of the host.
 *          type        - The type of the connection (Q.931/H.245).
 *          address     - Address to listen on
 *
 * returned value
 *          cmTransOK   -  proceed with listen
 *          cmTransIgnoreMessage - do not listen
 **************************************************************************************/
    TRANSERR (*cmEvTransHostListenT)(
            IN HSTRANSHOST          hsTransHost,
            IN HATRANSHOST          haTransHost,
            IN TRANSCONNTYPE        type,
            IN cmTransportAddress   *address);

typedef
/**************************************************************************************
 * cmEvTransHostListening (CALLBACK)
 *
 * Purpose: To report to the user that we are listening on a TCP connections
 *
 *
 * Input:   hsTransHost - The stack handle of the host.
 *          haTransHost - The application handle of the host.
 *          type        - The type of the connection (Q.931/H.245).
 *          address     - Address of listening socket
 *          error       - RV_TRUE if listen has failed
 *
 **************************************************************************************/
    TRANSERR (*cmEvTransHostListeningT)(
            IN HSTRANSHOST          hsTransHost,
            IN HATRANSHOST          haTransHost,
            IN TRANSCONNTYPE        type,
            IN cmTransportAddress   *address,
            IN RvBool               error);

typedef
/**************************************************************************************
 * cmEvTransHostConnecting (CALLBACK)
 *
 * Purpose: To report to the user that we are about to connect to a TCP address
 *
 *
 * Input:   hsTransHost - The stack handle of the host.
 *          haTransHost - The application handle of the host.
 *          type        - The type of the connection (Q.931/H.245).
 *          address     - Address to connct to
 *
 * returned value
 *          cmTransOK   -  proceed with connect
 *          cmTransIgnoreMessage - do not connect
 **************************************************************************************/
    TRANSERR (*cmEvTransHostConnectingT)(
            IN HSTRANSHOST          hsTransHost,
            IN HATRANSHOST          haTransHost,
            IN TRANSCONNTYPE        type,
            IN cmTransportAddress   *address);

typedef  struct
{
    cmEvTransHostConnectedT             cmEvTransHostConnected;
    cmEvTransHostClosedT                cmEvTransHostClosed;
    cmEvTransNewRawMessageT             cmEvTransNewRawMessage;
    cmEvTransSendRawMessageT            cmEvTransSendRawMessage;
    cmEvTransHostNewMessageT            cmEvTransHostNewMessage;
    cmEvTransHostBadMessageT            cmEvTransHostBadMessage;
    cmEvTransHostMultiplexChangeStateT  cmEvTransHostMultiplexChangeState;
    cmEvTransHostListenT                cmEvTransHostListen;
    cmEvTransHostListeningT             cmEvTransHostListening;
    cmEvTransHostConnectingT            cmEvTransHostConnecting;
} TRANSHOSTEVENTS;

/**************************************************************************************
 *                    A P I
 **************************************************************************************/

/******************************************************************************
 * cmTransInit
 * ----------------------------------------------------------------------------
 * General: Initialize the entire transport module
 *
 * Return Value: A handle to the entire transport module or NULL on failure.
 * ----------------------------------------------------------------------------
 * Arguments:
 * Input:  hAppATrans              - The application handle to the entire transport module.
 *         hPvt                    - The handle to the stack's PVT.
 *         selEngine               - select engine to use.
 *         numOfSessions           - The maximal amount of session elements to allocate.
 *         extraConnections        - Number for extra connections to allocate.
 *         poolSizeInKB            - maximum amount of storage for messages before send.
 *         poolElemSize            - maximum non-fragmented storage for messages.
 *         maxMessageSize          - Maximal size of encoded message.
 *         annexESupported         - Do we support annex E.
 *         numOfListeningAddresses - Number of listening addresses of each type.
 *         portRange               - Port range to use.
 *         logMgr                  - Log manager to use.
 * Output: None.
 *****************************************************************************/
HAPPTRANS cmTransInit(IN HAPPATRANS      hAppATrans,
                      IN HPVT            hPvt,
                      IN RvSelectEngine* selEngine,
                      IN int             numOfSessions,
                      IN int             extraConnections,
                      IN int             poolSizeInKB,
                      IN int             poolElemSize,
                      IN int             maxMessageSize,
                      IN RvBool          annexESupported,
                      IN RvInt           numOfListeningAddresses,
                      IN RvPortRange*    portRange,
                      IN RvLogMgr*       logMgr);

/******************************************************************************
 * cmTransStart
 * ----------------------------------------------------------------------------
 * General: To start the listening process on TPKT and/or Annex E.
 *
 * Return Value: cmTransOK on success.
 *               cmTransErr on failure.
 * ----------------------------------------------------------------------------
 * Arguments:
 * Input:  happTrans        - The handle to the instance of the transport module.
 *         tpktAddresses    - PVT node holding Q.931 TPKT listening addresses.
 *                            Of type "SEQUENCE OF TransportAddress".
 *         annexEAddresses  - List of annex E listening addresses.
 *                            Of type "SEQUENCE OF TransportAddress".
 *         localAddress     - The local address as was received from the configuration.
 *         annexEParams     - Annex E related parameters.
 * Output: None.
 *****************************************************************************/
TRANSERR cmTransStart(IN HAPPTRANS          happTrans,
                      IN RvPvtNodeId        tpktAddresses,
                      IN RvPvtNodeId        annexEAddresses,
                      IN cmTransportAddress *localAddress,
                      IN CMTRANSANNEXEPARAM *annexEParams);

/**************************************************************************************
 * cmTransStop
 *
 * Purpose: Stops all the listening processes that were started by cmTransStart.
 *
 * Input:   hAppTrans - A handle to the entire transport module
 *
 * Output:  None.
 *
 **************************************************************************************/
TRANSERR cmTransStop(IN HAPPTRANS hAppTrans);

/**************************************************************************************
 * cmTransEnd
 *
 * Purpose: Shuts down the module and deallocates all its components.
 *
 * Input:   hAppTrans - A handle to the entire transport module
 *
 * Output:  None.
 *
 **************************************************************************************/
TRANSERR cmTransEnd(IN HAPPTRANS hAppTrans);

/**************************************************************************************
 * cmTransCreateSession
 *
 * Purpose: Creates a new session element according to its parameters.
 *
 * Input:   hAppTrans       - A handle to the entire transport module
 *          haTranSession   - An application handle to be set to the session, ususally
 *                            would be the call handle that is associated with this session.
 *          hsTransHost     - handle of the host related to this session
 *
 * Output:  hsTranSession   - An handle to the created session element
 *
 **************************************************************************************/
TRANSERR cmTransCreateSession(  IN  HAPPTRANS       hAppTrans,
                                IN  HATRANSSESSION  haTransSession,
                                IN  HSTRANSHOST     hsTransHost,
                                OUT HSTRANSSESSION  *hsTransSession);



/**************************************************************************************
 * cmTransDrop
 *
 * Purpose: Drop a session (put its state in Idle).
 *
 * Input:   hsTranSession   - An handle to the session element
 *
 * Output:  None.
 *
 **************************************************************************************/
TRANSERR cmTransDrop(IN HSTRANSSESSION hsTransSession);


/**************************************************************************************
 * cmTransCloseSession
 *
 * Purpose: Deletes a session element.
 *
 * Input:   hsTranSession   - An handle to the session element
 *
 * Output:  None.
 *
 **************************************************************************************/
TRANSERR cmTransCloseSession(IN HSTRANSSESSION hsTransSession);

/**************************************************************************************
 * cmTransCreateHost
 *
 * Purpose: Creates a new host element according to its parameters.
 *
 * Input:   hAppTrans   - A handle to the entire transport module
 *          haTranHost  - An application handle to be set to the host element.
 *          relatedSession - handle to a related session, may be NULL.
 *
 * Output:  hsTranHost  - An handle to the created host element
 *
 **************************************************************************************/
TRANSERR cmTransCreateHost( IN  HAPPTRANS       hAppTrans,
                            IN  HSTRANSSESSION  relatedSession,
                            IN  HATRANSHOST     haTransHost,
                            OUT HSTRANSHOST    *hsTransHost);

/**************************************************************************************
 * cmTransCloseHost
 *
 * Purpose: Deletes a host element. Will notify all its associates sessions.
 *
 * Input:   hsTranHost  - An handle to the host element
 *
 * Output:  None.
 *
 **************************************************************************************/
TRANSERR cmTransCloseHost(IN HSTRANSHOST hsTransHost);

/**************************************************************************************
 * cmTransSetSessionParam
 *
 * Purpose: Sets a specific parameter for the given session element.
 *
 * Input:   hsTranSession   - An handle to the session element
 *          param           - The name of the parameter to be set.
 *          value           - An integer or pointer to set as the new parameter.
 *
 * Output:  None.
 *
 **************************************************************************************/
TRANSERR cmTransSetSessionParam(IN HSTRANSSESSION       hsTransSession,
                                IN TRANSSESSIONPARAM    param,
                                IN const void           *value);

/**************************************************************************************
 * cmTransGetSessionParam
 *
 * Purpose: Gets a specific parameter from a given session element.
 *
 * Input:   hsTranSession   - An handle to the session element
 *          param           - The name of the parameter to get.
 *
 * Output:  value           - An integer or pointer which is the value of the parameter.
 *
 **************************************************************************************/
TRANSERR cmTransGetSessionParam(IN  HSTRANSSESSION      hsTransSession,
                                IN  TRANSSESSIONPARAM   param,
                                OUT void                *value);

/**************************************************************************************
 * cmTransSetHostParam
 *
 * Purpose: Sets a specific parameter for the given host element.
 *
 * Input:   hsTranHost  - An handle to the host element
 *          param       - The name of the parameter to be set.
 *          value       - An integer or pointer to set as the new parameter.
 *          force       - In case of multiplexing parameters force the sending of FACILITY
 *                        to the remote with the new parameters.
 *
 * Output:  None.
 *
 **************************************************************************************/
TRANSERR cmTransSetHostParam(   IN HSTRANSHOST          hsTransHost,
                                IN TRANSHOSTPARAM       param,
                                IN const void           *value,
                                IN RvBool               force);

/**************************************************************************************
 * cmTransGetHostParam
 *
 * Purpose: Gets a specific parameter from a given host element.
 *
 * Input:   hsTranHost  - An handle to the host element
 *          param       - The name of the parameter to get.
 *
 * Output:  value       - An integer or pointer which is the value of the parameter.
 *
 **************************************************************************************/
TRANSERR cmTransGetHostParam(   IN  HSTRANSHOST     hsTransHost,
                                IN  TRANSHOSTPARAM  param,
                                OUT void            *value);

/**************************************************************************************
 * cmTransSetSessionEventHandler
 *
 * Purpose: Sets the event handlers' pointers for session related callbacks
 *
 * Input:   hAppTrans           - A handle to the entire transport module
 *          transSessionEvents  - A structure with the pointers to the callbacks
 *          size                - The size of that structure.
 *
 * Output:  None.
 *
 **************************************************************************************/
TRANSERR cmTransSetSessionEventHandler( IN HAPPTRANS            hAppTrans,
                                        IN TRANSSESSIONEVENTS   *transSessionEvents,
                                        IN int                  size);

/**************************************************************************************
 * cmTransGetSessionEventHandler
 *
 * Purpose: Gets the event handlers' pointers for session related callbacks
 *
 * Input:   hAppTrans           - A handle to the entire transport module
 *          size                - The size of the given structure.
 *
 * Output:  transSessionEvents  - A structure with the pointers to the callbacks
 *
 **************************************************************************************/
TRANSERR cmTransGetSessionEventHandler( IN  HAPPTRANS           hAppTrans,
                                        OUT TRANSSESSIONEVENTS  *transSessionEvents,
                                        IN  int                 size);

/**************************************************************************************
 * cmTransSetHostEventHandler
 *
 * Purpose: Sets the event handlers' pointers for host related callbacks
 *
 * Input:   hAppTrans       - A handle to the entire transport module
 *          transHostEvents - A structure with the pointers to the callbacks
 *          size            - The size of that structure.
 *
 * Output:  None.
 *
 **************************************************************************************/
TRANSERR cmTransSetHostEventHandler(    IN HAPPTRANS        hAppTrans,
                                        IN TRANSHOSTEVENTS  *transHostEvents,
                                        IN int              size);

/**************************************************************************************
 * cmTransGetHostEventHandler
 *
 * Purpose: Gets the event handlers' pointers for host related callbacks
 *
 * Input:   hAppTrans       - A handle to the entire transport module
 *          size            - The size of the given structure.
 *
 * Output:  transHostEvents - A structure with the pointers to the callbacks
 *
 **************************************************************************************/
TRANSERR cmTransGetHostEventHandler(    IN  HAPPTRANS       hAppTrans,
                                        OUT TRANSHOSTEVENTS *transHostEvents,
                                        IN  int             size);

/**************************************************************************************
 * cmTransSetAddress
 *
 * Purpose: sets the address, local and remote, or a host for a given session.
 *          This routine serves both Q.931 (TPKT & annex E) and H.245 connections.
 *
 * Input:   hsTransSession          - the handle to the session.
 *          localAddress            - the local address to connect from or listen on.
 *          remoteAddress           - The remote TPKT address to connect to.
 *          annexEremoteAddress     - The remote annex E address to connect to.
 *          hsTransHost             - An optional host that overrides the given addresses.
 *          type                    - Q.931 TPKT or H.245 addresses.
 *          newMultiplex            -   RV_TRUE:  create new host even if multiplexed
 *                                      RV_FALSE: for multiplex use existing host, if exists.
 *
 * Output:  None.
 *
 * Returned Value:  cmTransErr            - In case that an error occured.
 *                  cmTransNotMultiplexed - The given host is not multiplexed.
 *                  cmTransOK             - In case that the connection is already opened.
 *
 **************************************************************************************/
TRANSERR cmTransSetAddress(IN    HSTRANSSESSION      hsTransSession,
                           INOUT cmTransportAddress  *localAddress,
                           IN    cmTransportAddress  *remoteAddress,
                           IN    cmTransportAddress  *annexEremoteAddress,
                           IN    HSTRANSHOST         hsTransHost,
                           IN    TRANSCONNTYPE       type,
                           IN    RvBool              newMultiplex);


/**************************************************************************************
 * cmTransHostTpktSetAddress
 *
 * Purpose: sets the remote address. This routine serves Q.931 (TPKT only)
 *
 * Input:   remoteAddress           - The remote TPKT address to connect to.
 *          hsTransHost             - An optional host that overrides the given addresses.
 *
 * Output:  None.
 *
 * Returned Value:  cmTransErr            - In case that an error occured.
 *                  cmTransNotMultiplexed - The given host is not multiplexed.
 *                  cmTransOK             - In case that the connection is already opened.
 **************************************************************************************/
TRANSERR cmTransHostTpktSetAddress(IN    HSTRANSHOST         hsTransHost,
                                   IN    cmTransportAddress  *remoteAddress);


/**************************************************************************************
 * cmTransQ931Connect
 *
 * Purpose: Starts the process of connecting on behalf of the given session.
 *          For regular connection this will initiate a connect procedure,
 *          for multiplexed operation on an existing connection, this will
 *          report that a connection was established.
 *
 * Input:   hsTransSession  - the handle to the session.
 *
 * Output:  None.
 *
 * Returned Value:  cmTransWouldBlock - In case that a connect procedure was instigated but
 *                                      not yet completed.
 *                  cmTransOK         - In case that the connection is already opened.
 *
 **************************************************************************************/
TRANSERR cmTransQ931Connect(IN HSTRANSSESSION   hsTransSession);


/**************************************************************************************
 * cmTransHostTpktConnect
 *
 * Purpose: Used to connect alternate EPs when primary connection fails.
 *          Starts the process of connecting on behalf of the given session.
 *          For regular connection only!
 *
 * Input:   hsTransSession  - the handle to the session.
 *
 * Output:  None.
 *
 * Returned Value:  cmTransWouldBlock - In case that a connect procedure was instigated but
 *                                      not yet completed.
 *                  cmTransOK         - In case that the connection is already opened.
 *
 **************************************************************************************/
TRANSERR cmTransHostTpktConnect(IN HSTRANSSESSION   hsTransSession);


/**************************************************************************************
 * cmTransSendMessage
 *
 * Purpose: Encodes and sends a message for the given session thru its host connection.
 *
 * Input:   hsTransSession  - the handle to the session.
 *          pvtNode         - The pvt of the given decoded message.
 *          type            - The type of the message (Q.931/H.245)
 *
 * Output:  None.
 *
 * Returned Value:  cmTransWouldBlock - In case that there aren't enough buffers.
 *                  cmTransOK         - In case that the send was successful.
 *                  cmTransErr        - In case of fatal error.

 *
 **************************************************************************************/
TRANSERR cmTransSendMessage(IN HSTRANSSESSION   hsTransSession,
                            IN int              pvtNode,
                            IN TRANSTYPE        type);

/**************************************************************************************
 * cmTransSendH450Message
 *
 * Purpose: Sends a tunneled encoded message for the given session thru its host connection.
 *
 * Input:   hsTransSession  - the handle to the session.
 *          buffer          - The encoded tunneled message.
 *          size            - The size of the encoded message.
 *          flags:
 *             CM_H450_NO_FLAGS - will send on the next outgoing message, and will
 *                         initiate a facility messgae if call is connected.
 *             CM_H450_FORCE    - will force the stack to send a facility message
 *                         with the APDU.
 *             CM_H450_ALERTING - will send the APDU only with an alerting or a
 *                         connect message
 *
 * Output:  None.
 *
 * Returned Value:  cmTransWouldBlock - Last message was not sent yet, can't accept new one.
 *                  cmTransOK         - In case that the send was successful.
 *                  cmTransErr        - In case of fatal error.
 *
 **************************************************************************************/
TRANSERR cmTransSendH450Message(IN HSTRANSSESSION   hsTransSession,
                                IN RvUint8          *buffer,
                                IN int              size,
                                IN RvUint           flags);

/**************************************************************************************
 * cmTransSetH450Element
 *
 * Purpose: Sets the H.450 elements to send in the next outgoin message.
 *
 * Input:   hsTransSession  - the handle to the session.
 *          elementNodeId   - PVT node ID of the new H.450 element.
 *
 * Output:  None.
 *
 * Returned Value:  cmTransOK         - In case that the send was successful.
 *                  cmTransErr        - In case of fatal error.
 *
 **************************************************************************************/
TRANSERR cmTransSetH450Element(IN HSTRANSSESSION   hsTransSession,
                               IN RvPvtNodeId      elementNodeId);

/**************************************************************************************
 * cmTransSendTunneledMessage
 *
 * Purpose: Sends a tunneled encoded message for the given session thru its host connection.
 *
 * Input:   hsTransSession  - the handle to the session.
 *          msg             - The node id of the encoded tunneled message.
 *          type            - The type of the message (AnnexM/AnnexL etc.)
 *          force           - Should we send a facility immediately with the message.
 *
 * Output:  None.
 *
 * Returned Value:  cmTransWouldBlock - Last message was not sent yet, can't accept new one.
 *                  cmTransOK         - In case that the send was successful.
 *                  cmTransErr        - In case of fatal error.
 *
 **************************************************************************************/
TRANSERR cmTransSendTunneledMessage(IN HSTRANSSESSION   hsTransSession,
                                    IN int              msg,
                                    IN TRANSTYPE        type,
                                    IN RvBool           force);

/**************************************************************************************
 * cmTransEstablishControl
 *
 * Purpose: Starts a H.245 control for a given session after fast start or no control
 *          exists. If tunneling allowed, will use tunneling, else will open a "true"
 *          H.245 connection.
 *
 * Input:   hsTransSession  - the handle to the session.
 *
 * Output:  None.
 *
 **************************************************************************************/
TRANSERR cmTransEstablishControl(IN HSTRANSSESSION hsTransSession);

/**************************************************************************************
 * cmTransSwitchToSeparate
 *
 * Purpose: Starts a "true" H.245 control connection for a given session.
 *          Can be called when the call is in Fast Start, tunneling or no control.
 *
 * Input:   hsTransSession  - the handle to the session.
 *
 * Output:  None.
 *
 **************************************************************************************/
TRANSERR cmTransSwitchToSeparate(IN HSTRANSSESSION hsTransSession);

/**************************************************************************************
 * cmTransCreateControlSession
 *
 * Purpose: Starts a "true" H.245 control connection, in case that H.245 is allowed.
 *
 * Input:   hsTransSession  -       the handle to the session with which the new H.245
 *                                  control is to be associated.
 *          addr            -       the address to listen or connect to.
 *          startListen     -       RV_TRUE:  start listening on the address.
 *                                  RV_FALSE: try to connect to the addr.
 *          nullControlSession -    RV_TRUE:  Create a dummy control session that is not connected
 *                                         to anywhere.
 *                                  RV_FALSE: Create a normal control session according to
 *                                         the given params.
 *
 * Output:  None.
 *
 **************************************************************************************/
TRANSERR cmTransCreateControlSession(IN  HSTRANSSESSION     hsTransSession,
                                     IN  cmTransportAddress *addr,
                                     IN  RvBool             startListen,
                                     IN  RvBool             nullControlSession);

/**************************************************************************************
 * cmTransCloseControlSession
 *
 * Purpose: closes an H.245 connection for a given session.
 *
 * Input:   hsTransSession  - The handle of the new or old sesson associated with the
 *                            new H.245 control.
 *
 * Output: None.
 *
 * returned value: cmTransErr - in case of error, cmTransOK - otherwise
 *
 **************************************************************************************/
TRANSERR cmTransCloseControlSession(IN  HSTRANSSESSION  hsTransSession);

/**************************************************************************************
 * cmTransTryControlAfterACF
 *
 * Purpose: sees if H245 control session should be oprned after ACF.
 *
 * Input:   hsTransSession  - The handle of the new or old sesson associated with the
 *                            new H.245 control.
 *
 * Output: None.
 *
 * returned value: cmTransErr - in case of error, cmTransOK - otherwise
 *
 **************************************************************************************/
TRANSERR cmTransTryControlAfterACF(IN  HSTRANSSESSION  hsTransSession);

/**************************************************************************************
 * cmTransHasControlSession
 *
 * Purpose: reports whether an H.245 connection exists and connected.
 *
 * Input:   hsTransSession  - The handle of the sesson associated with the H.245 control.
 *
 * Output: None.
 *
 * returned value: RV_TRUE - The h245 exists and connected; RV_FALSE - Otherwise
 *
 **************************************************************************************/
RvBool cmTransHasControlSession(IN  HSTRANSSESSION    hsTransSession);

/**************************************************************************************
 * cmTransHasControlSession
 *
 * Purpose: reports whether an H.245 connection exists and connected.
 *
 * Input:   hsTransSession  - The handle of the sesson associated with the H.245 control.
 *
 * Output:  addr            - local address of the H.245 connection
 *
 * returned value: RV_TRUE - The h245 exists and connected; RV_FALSE - Otherwise
 *
 **************************************************************************************/
void cmTransGetGoodAddressForH245(IN    HSTRANSSESSION     hsTransSession,
                                  INOUT cmTransportAddress *addr);

/**************************************************************************************
 * cmTransGetGoodAddress
 *
 * Purpose: calculates the local address of the h.245
 *
 * Input:   happTrans       - The handle of the transport module.
 *
 * Output:  addr            - local address of the H.245 connection
 *
 * returned value: RV_TRUE - The h245 exists and connected; RV_FALSE - Otherwise
 *
 **************************************************************************************/
void cmTransGetGoodAddress(IN    HAPPTRANS          happTrans,
                           INOUT cmTransportAddress *addr);

/**************************************************************************************
 * cmTransGetSessionByMessage
 *
 * Purpose: Find a session by an incoming message.
 *
 * Input:   hsTransHost     - The handle of the host this message arrived on.
 *          pvtNode         - The pvt of the given decoded message.
 *
 * Output:  hsTransSession  - The handle of the session that was found.
 *          haTransSession  - The application handle of the session that was found.
 *
 * Returned Value:  cmTransOK         - In case that the send was successful (also if
 *                                      session not found because it's a general message).
 *                  cmTransErr        - In case of fatal error.
 *
 **************************************************************************************/
TRANSERR cmTransGetSessionByMessage(
    IN  HSTRANSHOST     hsTransHost,
    IN  RvPvtNodeId     pvtNode,
    OUT HSTRANSSESSION  *hsTransSession,
    OUT HATRANSSESSION  *haTransSession);

/**************************************************************************************
 * cmTransGetHApp
 *
 * Purpose: gets the hApp element according to the given host
 *
 * Input:   hsTransHost  - The handle of the host.
 *
 * returned value:  hAppATrans   - The user associated handle to the module instance.
 *
 **************************************************************************************/
HAPPATRANS cmTransGetHApp(IN HSTRANSHOST hsTransHost);

/**************************************************************************************
 * cmTransSetHostApplHandle
 *
 * Purpose: Changes host application handle
 *
 * Input:   hsTransHost  - The handle of the host.
 *          haTransHost  - The new host application handle.
 *
 * Output:  None.
 *
 **************************************************************************************/
TRANSERR cmTransSetHostApplHandle(IN  HSTRANSHOST hsTransHost,
                                  IN  HATRANSHOST haTransHost);

/**************************************************************************************
 * cmTransGetHostApplHandle
 *
 * Purpose: Retrieves host application handle
 *
 * Input:   hsTransHost  - The handle of the host.
 *
 * Output:  haTransHost  - The host application handle.
 *
 **************************************************************************************/
TRANSERR cmTransGetHostApplHandle(IN  HSTRANSHOST  hsTransHost,
                                  OUT HATRANSHOST *haTransHost);


/******************************************************************************
 * cmTransHostSendMessage
 * ----------------------------------------------------------------------------
 * General: Send a message on the host.
 *
 * Return Value: cmTransOK on success, other on failure.
 * ----------------------------------------------------------------------------
 * Arguments:
 * Input:  hsTransHost  - The handle of the host.
 *         pvtNode      - The pvtNodeId of the message to be sent.
 * Output: none
 *****************************************************************************/
TRANSERR cmTransHostSendMessage(
    IN HSTRANSHOST  hsTransHost,
    IN RvPvtNodeId  pvtNode);


/******************************************************************************
 * cmTransHostSendRawMessage
 * ----------------------------------------------------------------------------
 * General: Send a raw encoded message on the host.
 *
 * Return Value: cmTransOK on success, other on failure.
 * ----------------------------------------------------------------------------
 * Arguments:
 * Input:  hsTransHost  - The handle of the host.
 *         buffer       - Buffer to send as the message.
 *         bufferSize   - Size of buffer to send.
 * Output: none
 *****************************************************************************/
TRANSERR cmTransHostSendRawMessage(
    IN HSTRANSHOST  hsTransHost,
    IN RvUint8      *buffer,
    IN RvSize_t     bufferSize);


/******************************************************************************
 * cmTransHostReceiveRawMessage
 * ----------------------------------------------------------------------------
 * General: Receive a raw Q.931 encoded message on the host.
 *
 * Return Value: cmTransOK on success, other on failure.
 * ----------------------------------------------------------------------------
 * Arguments:
 * Input:  hsTransHost  - The handle of the host.
 *         buffer       - Buffer to receive as the message.
 *         bufferSize   - Size of buffer to receive.
 * Output: none
 *****************************************************************************/
TRANSERR cmTransHostReceiveRawMessage(
    IN HSTRANSHOST  hsTransHost,
    IN RvUint8      *buffer,
    IN RvSize_t     bufferSize);


/******************************************************************************
 * cmTransHostTpktClose
 * ----------------------------------------------------------------------------
 * General: Close Tpkt connection on the host
 *
 * Return Value: cmTransOK (on success).
 * ----------------------------------------------------------------------------
 * Arguments:
 * Input:  hsTransHost  - The handle of the host.
 * Output: none
 *****************************************************************************/
TRANSERR cmTransHostTpktClose(IN HSTRANSHOST  hsTransHost);


/******************************************************************************
 * cmTransSetConnection
 * ----------------------------------------------------------------------------
 * General: Replaces a session's (and call) host with the given hConn.
 *
 * Return Value: cmTransOK on success, other on failure.
 * ----------------------------------------------------------------------------
 * Arguments:
 * Input:  hAppTrans       - The handle to the transport module.
 *         hsTransSession  - The handle of the session.
 *         hConn           - The connection to set.
 *         bIsQ931Conn     - RV_TRUE if the connection is a Q931 host.
 * Output: none
 *****************************************************************************/
TRANSERR cmTransSetConnection(IN HAPPTRANS      hAppTrans,
                              IN HSTRANSSESSION hsTransSession,
                              IN HSTRANSHOST    hConn,
                              IN RvBool         bIsQ931Conn);


/*---------------------------------------------------------------------------------------
 * dummyControlSession :
 *
 * defines if the control session is dummy
 *
 * Input:  hsTranSession   - An handle to the created session element
 * Output: none
 * Return: 1 - if control session is DUMMY.
 *         0 - otherwise
 *---------------------------------------------------------------------------------------*/
RvBool  dummyControlSession(IN HSTRANSSESSION hsTransSession);


/*---------------------------------------------------------------------------------------
 * triggerH245AfterACF :
 *
 * triggers the setup/early H.245 connection after ACF was received for the call
 *
 * Input:  hsTranSession - handle to the call's session element
 * Output: none
 * Return: cmTransOK
 *---------------------------------------------------------------------------------------*/
TRANSERR triggerH245AfterACF(IN HSTRANSSESSION hsTransSession);


/************************************************************************
 * transParentNew
 * purpose: Set a new lock pointer to the given EMA element
 * input  : hTransport     - handle to the transport globals
 *          emaElem        - The EMA element getting a new lock
 * output : none
 * return : RV_OK on success, negative o.w.
 ************************************************************************/
RvStatus transParentNew(
    IN HAPPTRANS    hTransport,
    IN void*        emaElem);


/************************************************************************
 * transParentShare
 * purpose: Set the lock pointer of the first EMA element to that of the
 *          second
 * input  : hTransport     - handle to the transport globals
 *          emaElem        - The EMA element getting a lock
 *          sharingEmaElem - The EMA element sharing its lock
 * output : none
 * return : RV_OK on success, negative o.w.
 ************************************************************************/
RvStatus transParentShare(
    IN HAPPTRANS    hTransport,
    IN void*        emaElem,
    IN void*        sharingEmaElem);


/************************************************************************
 * transParentReplace
 * purpose: Set the lock pointer of several EMA elements to that of the
 *          another
 * input  : hTransport     - handle to the transport globals
 *          emaElems       - The EMA elements array getting a lock (NULL
 *                           terminated), all the elements using the lock
 *          sharingEmaElem - The EMA element sharing its lock
 * output : none
 * return : RV_OK on success, negative o.w.
 ************************************************************************/
RvStatus transParentReplace(
    IN HAPPTRANS    hTransport,
    IN void**       emaElems,
    IN void*        sharingEmaElem);


/************************************************************************
 * transParentRemove
 * purpose: Remove the lock pointer from the given EMA element
 * input  : hTransport - handle to the transport globals
 *          emaElem    - The EMA element
 * output : none
 * return : RV_OK on success, negative o.w.
 ************************************************************************/
RvStatus transParentRemove(
    IN HAPPTRANS    hTransport,
    IN void*        emaElem);


#ifdef __cplusplus
}
#endif

#endif  /* _TRANSPORT_H */

