//AVCONProduct.h
#ifndef __AVCONPRODUCT_H__
#define __AVCONPRODUCT_H__

#define AVCON_PRODUCT_NORMAL	0
#define AVCON_PRODUCT_RS		1
#define AVCON_PRODUCT_WJ		2
#define AVCON_PRODUCT_NFH		3
#define AVCON_PRODUCT_PICC		4
#define AVCON_PRODUCT_XF_D		5

#endif
