#ifndef _HPMCGW_DEFINE
#define _HPMCGW_DEFINE

//矩阵切换命令
#define	MON_CMD_MATRIX_CHANGE	"MON_CMD_MATRIX_CHANGE"		//矩阵切换命令头
#define MON_MATRIX_GETINFO		"MON_MATRIX_GETINFO"		//获取矩阵信息
#define MON_MATRIX_INFO_START   "MON_MATRIX_INFO_START"		//开始
#define MON_MATRIX_INFO_DETAIL	"MON_MATRIX_INFO_DETAIL"	//矩阵信息
#define MON_MATRIX_INFO_END		"MON_MATRIX_INFO_END"		//结束
//命令内容KEY
#define MON_MATRIX_NAME			"MON_MATRIX_NAME"			//矩阵源名称
#define MON_MATRIX_CHANNAME		"MON_MATRIX_CHANNAME"		//矩阵通道名称
#define MON_MATRIX_INPUTCOUNT	"MON_MATRIX_INPUTCOUNT"		//矩阵输入数量
#define MON_MATRIX_INPUT		"MON_MATRIX_INPUT"			//矩阵输入通道号1索引值
#define MON_MATRIX_DATA			"MON_MATRIX_DATA"			//矩阵信息压缩数据
#define MON_MATRIX_BEGIN_INDEX	"MON_MATRIX_BEGIN_INDEX"	//索引开始
#define	MON_MATRIX_END_INDEX	"MON_MATRIX_END_INDEX"		//索引结束

#endif