#pragma once

#define		PLAY_EVENT_MESSAGE			WM_USER+100	//WPARAM=PLAY_EVENT_XXXX, LPARAM=parameter
enum {
	PLAY_EVENT_TIMESTAMP=1,
	PLAY_EVENT_OVER,
	PLAY_EVENT_START_BUFFER,
	PLAY_EVENT_STOP_BUFFER,
	PLAY_EVENT_START_SEEK,
	PLAY_EVENT_STOP_SEEK,
	PLAY_EVENT_PAUSE,
	PLAY_EVENT_TIMEOSD,
	PLAY_EVENT_MUTE,
	PLAY_EVENT_VOLUME,
	PLAY_EVENT_MODECHANGED,
	PLAY_EVENT_SELECTED,
	PLAY_EVENT_MENU,		//菜单
	PLAY_EVENT_FULLSCREEN, //TRUE 全屏模式， FALSE 退出全屏模式 //PLAY_EVENT_RESTORE,
	PLAY_EVENT_DOUBLESIZE,
	PLAY_EVENT_STREAM,
	PLAY_EVENT_VIDEO_CHANGED,
	PLAY_EVENT_NEWSTREAM,
	PLAY_EVENT_ERROR,
	PLAY_EVENT_DURATION_CHANGED,
	PLAY_EVENT_PLAY,
	PLAY_EVENT_ENCODE
};

//播放模式
enum {
	PLAY_MODE_NORMAL=0,		//正常播放
	PLAY_MODE_FRAME,		//单帧进
	PLAY_MODE_X,			//慢进	（1/2X）
	PLAY_MODE_2X,			//快进	（2X）
	PLAY_MODE_4X,			//快进	（4X）
	PLAY_MODE_8X,			//快进	（8X）
	PLAY_MODE_16X,			//快进	（16X）
	PLAY_MODE_NULL=15,		//进退间隔
	PLAY_MODE_FRAME_REVERSE,//单帧退
	PLAY_MODE_X_REVERSE,	//慢退	（1/2X）
	PLAY_MODE_2X_REVERSE,	//快退	（2X）
	PLAY_MODE_4X_REVERSE,	//快退	（4X）
	PLAY_MODE_8X_REVERSE,	//快退	（8X）
	PLAY_MODE_16X_REVERSE	//快退	（16X）
};
enum {
	PLAY_STYLE_FILE_INFO=1,
	PLAY_STYLE_FILE_LIST=2,
	PLAY_STYLE_OSD_TIME=4,
	PLAY_STYLE_OSD_CHANNEL=8,
	PLAY_STYLE_OSD_STATUS=0x0010,
	PLAY_STYLE_MENU=0x0020,//禁用内置右键菜单,发送WM_NOTIFY::NM_RCLICK通知
	PLAY_SYTLE_FIXEDRATIO=0x00C0,
	PLAY_SYTLE_FULLSCREEN=0x0100
};
enum {
	PLAY_ERR_TIMEOUT,		//索引或数据缓存超时
	PLAY_ERR_PARSER=-4,		//文件解释错误
	PLAY_ERR_NOFILE=-3,		//文件不存在或读取失败
	PLAY_ERR_CONNECTED=-2,	//网络连接失败
	PLAY_ERR_FAILED=-1,
	PLAY_ERR_SUCCESS=0,		//
	PLAY_INF_RECONNECT,		//网络尝试重连
	PLAY_INF_CONNECTED,		//网络连接成功
	PLAY_INF_INDEXING,		//建或取索引
	PLAY_INF_BUFFERING,		//数据缓存中
};

enum 
{
	TM_1X1	= 0x0001,
	TM_2X2	= 0x0004,
	TM_3X3	= 0x0009,
	TM_4X4	= 0x0010,
	TM_5X5	= 0x0019,
	TM_6X6	= 0x0024,
	TM_7X7	= 0x0031,
	TM_8X8	= 0x0040,
	TM_9X9	= 0x0051,
	TM_RL5	= 0x0005,
	TM_RL6	= 0x0006,
	TM_RL8	= 0x0008,
	TM_RL10	= 0x000A,
	TM_RL12	= 12,
	TM_RL14 = 14,
	TM_RL18 = 18,
	TM_ALL  = 0xFFFF
};
